name = "ArrayInterface"
uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
version = "5.0.8"

[deps]
ArrayInterfaceCore = "30b0a656-2188-435a-8636-2ec0e6a096e2"
ArrayInterfaceBandedMatrices = "2e50d22c-5be1-4042-81b1-c572ed69783d"
ArrayInterfaceBlockBandedMatrices = "5331f1e9-51c7-46b0-a9b0-df4434785e0a"
ArrayInterfaceCuArrays = "3437ff42-decc-4d23-83d9-97c36d08d837"
ArrayInterfaceCUDA = "3e6d3b71-936e-4b08-8b74-7853fb4a8432"
ArrayInterfaceLabelledArrays = "e8e6c4e0-6dc8-4c5e-8daa-74cfef068049"
ArrayInterfaceOffsetArrays = "015c0d05-e682-4f19-8f0a-679ce4c54826"
ArrayInterfaceStaticArrays = "b0d46f97-bff5-4637-a19a-dd75974142cd"
ArrayInterfaceTracker = "a2b0951a-f94f-4742-8780-617792921f9b"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
ArrayInterfaceCore = "0.1"
ArrayInterfaceBandedMatrices = "0.1"
ArrayInterfaceBlockBandedMatrices = "0.1"
ArrayInterfaceCuArrays = "0.1" 
ArrayInterfaceCUDA = "0.1"
ArrayInterfaceLabelledArrays = "0.1"
ArrayInterfaceOffsetArrays = "0.1"
ArrayInterfaceStaticArrays = "0.1"
ArrayInterfaceTracker = "0.1"
Static = "0.6"
julia = "1.6"
